CREATE TYPE USER_LEVEL AS ENUM ('read', 'write', 'admin');

CREATE TABLE users (
    id                TEXT PRIMARY KEY,
    username          TEXT NOT NULL,
    display_name      TEXT NOT NULL,
    level             USER_LEVEL NOT NULL,
    password          TEXT NOT NULL,
    totp_secret       TEXT,
    invalidation_time BIGINT,
    settings          JSONB NOT NULL
);

CREATE TABLE projects (
    id         TEXT PRIMARY KEY,
    name       TEXT NOT NULL,
    image      TEXT NOT NULL,
    created_by TEXT, -- REFERENCES users(id) ON DELETE RESTRICT NOT NULL,
    created_on TIMESTAMPTZ NOT NULL
);

CREATE TABLE monitors (
    id           TEXT PRIMARY KEY,
    project_id   TEXT REFERENCES projects(id) ON DELETE CASCADE NOT NULL,
    name         TEXT NOT NULL,
    query        TEXT NOT NULL,
    count        INT NOT NULL,
    updated_at   TIMESTAMPTZ,
    since_id     TEXT 
);

CREATE TYPE JOB_STATUS AS ENUM  ('ready', 'done', 'failed');

CREATE TABLE jobs (
    monitor_id   TEXT REFERENCES monitors(id) ON DELETE CASCADE NOT NULL,
    job_type     TEXT NOT NULL ,
    submitted_at TIMESTAMPTZ NOT NULL,
    execute_at   TIMESTAMPTZ NOT NULL,
    last_id      TEXT NOT NULL,
    status       JOB_STATUS NOT NULL
);

CREATE INDEX ready_jobs ON jobs(status) WHERE status = 'ready';

CREATE TABLE tweets (
    id    TEXT PRIMARY KEY,
    tweet JSONB NOT NULL
);

CREATE TABLE monitor_tweets (
    monitor_id TEXT REFERENCES monitors(id) ON DELETE CASCADE NOT NULL,
    tweet_id   TEXT REFERENCES tweets(id) ON DELETE CASCADE NOT NULL,
    PRIMARY KEY(monitor_id, tweet_id)
);

CREATE TABLE media (
    id           TEXT PRIMARY KEY,
    s3_location  TEXT NOT NULL
);

-- avoid having to rewrite URL inside tweet bodies with this table
CREATE TABLE media_references (
    id           TEXT REFERENCES media(id) ON DELETE CASCADE NOT NULL,
    original_url TEXT NOT NULL
);
CREATE INDEX ON media_references(original_url);

CREATE INDEX ON monitor_tweets(monitor_id);
CREATE INDEX ON monitor_tweets(tweet_id);

CREATE TABLE tags (
    id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    color TEXT NOT NULL,
    label TEXT NOT NULL
);