version: '3'

services:
  postgres:
    image: postgres:10.5-alpine
    container_name: ferret-postgres
    ports:
      - 9002:5432
    environment:
      - POSTGRES_USER=ferret
      - POSTGRES_PASSWORD=ferret
      - POSTGRES_DB=ferret
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local
